### ISSUE TITLE
[bug] Fulvous error with storage root invalid

### ISSUE THREAD

**Issue by vimukthi-git** [centrifuge/centrifuge-chain#71]
When running fulvous, node panics with,
```
====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h22f0f1d19b29e46d (0x5570318b0ec0)
   1: std::panicking::rust_panic_with_hook::h057ff03eb4c8000f (0x5570319e9a59)
             at src/libstd/panicking.rs:478
   2: std::panicking::begin_panic::h01337335381120d3 (0x557031539645)
   3: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block::h46420a4b51db8b11 (0x55703153d8ac)
   4: centrifuge_chain_runtime::api::dispatch::h63face78c359dd4d (0x557031514a8d)
   5: std::panicking::try::do_call::h62e7477d6f4b75b4 (0x557030f33692)
   6: __rust_maybe_catch_panic (0x5570319eedea)
             at src/libpanic_unwind/lib.rs:85
   7: substrate_executor::native_executor::safe_call::h3cbd82ffde27a0a3 (0x557030cc9728)
   8: std::thread::local::LocalKey<T>::with::h8e36660e2af3b325 (0x557030a53127)
   9: <centrifuge_chain::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::h0913301dcc5bbd02 (0x557030891792)
  10: std::thread::local::LocalKey<T>::with::hada49c4683f7f063 (0x557030a5be3e)
  11: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::h4c4976f3f2d5fbc8 (0x557030e0ca66)
  12: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_call_with_native_else_wasm_strategy::h7a70dacfe7719c17 (0x557030e12122)
  13: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::hf54a9cd0e8c0c6eb (0x557030d9af96)
  14: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h3b2cc48f55fe45c5 (0x557030a024b8)
  15: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,PRA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hfa4176c6ffcdc91b (0x557030f173d6)
  16: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hf4b1416a1336ff4f (0x557030e56cce)
  17: core::task::poll::Poll<T>::map::h2800644b173cd077 (0x557030b0bd38)
  18: <futures_util::try_future::map_ok::MapOk<Fut,F> as core::future::future::Future>::poll::h44e75c53666d861d (0x5570307e100c)
  19: futures_util::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll::hf94a03e42d347958 (0x557030e3a9ad)
  20: <futures_util::try_stream::try_for_each::TryForEach<St,Fut,F> as core::future::future::Future>::poll::h1e4058bc162f42bf (0x557030b1ca59)
  21: futures_util::future::chain::Chain<Fut1,Fut2,Data>::poll::h7e04c1afbe139a43 (0x5570307eacda)
  22: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll::h8dbc10bf30d58049 (0x557030ef3776)
  23: <futures::future::select::Select<A,B> as futures::future::Future>::poll::h61fa2b5b8f541b6a (0x557030c31b2a)
  24: futures::future::chain::Chain<A,B,C>::poll::h6107eb89c39c9da2 (0x557030ea93ec)
  25: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::hf2217414ed5ab382 (0x557030d2bf3e)
  26: futures::task_impl::std::set::h1d6c7394509821f8 (0x55703173b292)
  27: std::panicking::try::do_call::h4da7ee154caa89f2 (0x55703173adf2)
  28: __rust_maybe_catch_panic (0x5570319eedea)
             at src/libpanic_unwind/lib.rs:85
  29: tokio_threadpool::task::Task::run::h0116a589554a280b (0x5570317384b9)
  30: tokio_threadpool::worker::Worker::run_task::h59c5abb9988e7e20 (0x557031731e55)
  31: tokio_threadpool::worker::Worker::run::h818f5066b41d5b52 (0x55703173132e)
  32: std::thread::local::LocalKey<T>::with::h1fcd9efb210f2dd2 (0x55703171bcde)
  33: std::thread::local::LocalKey<T>::with::h5fbd4053ce8d547c (0x55703171be9f)
  34: std::thread::local::LocalKey<T>::with::h16eaac48bb88b444 (0x55703171bb2b)
  35: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h5c979caac29cea17 (0x5570317208de)
  36: std::thread::local::LocalKey<T>::with::h01b9617282c3e29b (0x55703173ba63)
  37: std::thread::local::LocalKey<T>::with::h076aff392ca7ff3f (0x55703173bb9e)
  38: std::sys_common::backtrace::__rust_begin_short_backtrace::hd8e94618c1c47325 (0x557031733991)
  39: std::panicking::try::do_call::h9f90deaf148b6ba7 (0x55703173ae3c)
  40: __rust_maybe_catch_panic (0x5570319eedea)
             at src/libpanic_unwind/lib.rs:85
  41: core::ops::function::FnOnce::call_once{{vtable.shim}}::he5b73f6ee3ce78f5 (0x557031734610)
  42: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h805c3cc89d534c05 (0x5570319d71ff)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  43: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h9ebda9db5f03daf3 (0x5570319ee100)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
      std::sys_common::thread::start_thread::ha32838ccbb8a8179
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h6f10b78f26c98dc6
             at src/libstd/sys/unix/thread.rs:79
  44: start_thread (0x7f52c66166ba)
  45: clone (0x7f52c613641d)
  46: <unknown> (0x0)

Thread 'tokio-runtime-worker-1' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/4e1d637/srml/executive/src/lib.rs:319
```
This started happening after implementing child storage anchor state rent.

**Comment by vimukthi-git** [comment]
This was a deployment synchronisation issue where old leftover validators that were being scaled down were affecting state on new validators which are scaling up. This corrupted there state as if they were in the same network with older nodes. The solution was to make sure that older validator nodes are dead before the new ones are started in the cluster using the spinnaker pipeline.
cc @pstehlik @mikiquantum

**Comment by vimukthi-git** [comment]
similar issue encountered else where https://github.com/paritytech/substrate/issues/3580
